import { TimeZone } from "./types";

const students = [
    { "id": "S001", "name": "Ahan Kumar", "grade": "Grade 8", "score": 830, "accuracy": 96, "sessions": 68, "imageUrl": "p1.jpeg", "streak": 15, "hours": 120, skills: {
      vocabulary: 82,
      grammar: 78,
      punctuation: 80,
      listening: 85,
      speaking: 84,
    }, },
    { "id": "S002", "name": "Hvff", "grade": "Grade 7", "score": 295, "accuracy": 94, "sessions": 45, "imageUrl": "p2.jpeg", "streak": 12, "hours": 75, skills: {
      vocabulary: 82,
      grammar: 78,
      punctuation: 80,
      listening: 85,
      speaking: 84,
    }, },
    { "id": "S003", "name": "Flower Girl", "grade": "Grade 6", "score": 190, "accuracy": 93, "sessions": 38, "imageUrl": "p3.jpeg", "streak": 8, "hours": 60, skills: {
      vocabulary: 92,
      grammar: 88,
      punctuation: 91,
      listening: 90,
      speaking: 89,
    }, },
    { "id": "S004", "name": "June Child Test", "grade": "Grade 5", "score": 165, "accuracy": 92, "sessions": 32, "imageUrl": "p4.jpeg", "streak": 6, "hours": 58,
        skills: {
      vocabulary: 80,
      grammar: 67,
      punctuation: 65,
      listening: 86,
      speaking: 64,
    },
     },
    { "id": "S005", "name": "Hcdff", "grade": "Grade 4", "score": 160, "accuracy": 91, "sessions": 30, "imageUrl": "p5.jpeg", "streak": 5, "hours": 55, skills: {
      vocabulary: 82,
      grammar: 78,
      punctuation: 80,
      listening: 85,
      speaking: 84,
    }, },
    { "id": "S006", "name": "Eva", "grade": "Grade 3", "score": 145, "accuracy": 90, "sessions": 28, "imageUrl": "p6.jpeg", "streak": 4, "hours": 52, skills: {
      vocabulary: 76,
      grammar: 74,
      punctuation: 79,
      listening: 77,
      speaking: 75,
    }, },
    { "id": "S007", "name": "Sophia Kim", "grade": "Grade 2", "score": 138, "accuracy": 89, "sessions": 26, "imageUrl": "p7.jpeg", "streak": 4, "hours": 50, skills: {
      vocabulary: 85,
      grammar: 87,
      punctuation: 90,
      listening: 88,
      speaking: 86,
    }, },
    { "id": "S008", "name": "James Wilson", "grade": "Grade 6", "score": 132, "accuracy": 88, "sessions": 24, "imageUrl": "p8.jpeg", "streak": 3, "hours": 49, skills: {
      vocabulary: 90,
      grammar: 69,
      punctuation: 72,
      listening: 81,
      speaking: 73,
    }, },
    { "id": "S009", "name": "Olivia Davis", "grade": "Grade 5", "score": 128, "accuracy": 87, "sessions": 22, "imageUrl": "p9.jpeg", "streak": 3, "hours": 48, skills: {
      vocabulary: 96,
      grammar: 67,
      punctuation: 65,
      listening: 96,
      speaking: 64,
    }, },
    { "id": "S010", "name": "Liam Garcia", "grade": "Grade 1", "score": 120, "accuracy": 86, "sessions": 20, "imageUrl": "p10.jpeg", "streak": 2, "hours": 45, skills: {
      vocabulary: 92,
      grammar: 88,
      punctuation: 91,
      listening: 90,
      speaking: 89,
    }, },
    { "id": "S011", "name": "Noah Thompson", "grade": "Grade 4", "score": 115, "accuracy": 83, "sessions": 19, "imageUrl": "p11.jpeg", "streak": 2, "hours": 44, skills: {
      vocabulary: 94,
      grammar: 96,
      punctuation: 93,
      listening: 95,
      speaking: 97,
    }, },
    { "id": "S012", "name": "Ava Martinez", "grade": "Grade 3", "score": 110, "accuracy": 85, "sessions": 18, "imageUrl": "p12.jpeg", "streak": 1, "hours": 42, skills: {
      vocabulary: 82,
      grammar: 75,
      punctuation: 70,
      listening: 84,
      speaking: 76,
    }, },
    { "id": "S013", "name": "Mason Brown", "grade": "Grade 7", "score": 300, "accuracy": 92, "sessions": 40, "imageUrl": "p13.jpeg", "streak": 9, "hours": 70, skills: {
      vocabulary: 97,
      grammar: 66,
      punctuation: 69,
      listening: 85,
      speaking: 70,
    }, },
    { "id": "S014", "name": "Ethan Lee", "grade": "Grade 9", "score": 410, "accuracy": 95, "sessions": 55, "imageUrl": "p14.jpeg", "streak": 11, "hours": 88, skills: {
      vocabulary: 85,
      grammar: 79,
      punctuation: 76,
      listening: 88,
      speaking: 77,
    }, },
    { "id": "S015", "name": "Isabella Lopez", "grade": "Grade 8", "score": 270, "accuracy": 89, "sessions": 35, "imageUrl": "p15.jpeg", "streak": 6, "hours": 62, skills: {
      vocabulary: 90,
      grammar: 69,
      punctuation: 72,
      listening: 91,
      speaking: 73,
    }, },
    { "id": "S016", "name": "Sophia Chen", "grade": "Grade 7", "score": 390, "accuracy": 97, "sessions": 60, "imageUrl": "p16.jpeg", "streak": 10, "hours": 95, skills: {
      vocabulary: 94,
      grammar: 96,
      punctuation: 93,
      listening: 95,
      speaking: 97,
    }, },
    { "id": "S017", "name": "Liam Smith", "grade": "Grade 11", "score": 420, "accuracy": 94, "sessions": 72, "imageUrl": "p17.jpeg", "streak": 13, "hours": 110, skills: {
      vocabulary: 87,
      grammar: 78,
      punctuation: 80,
      listening: 85,
      speaking: 84,
    }, },
    { "id": "S018", "name": "Emily Clark", "grade": "Grade 10", "score": 250, "accuracy": 88, "sessions": 33, "imageUrl": "p18.jpeg", "streak": 5, "hours": 61, skills: {
      vocabulary: 85,
      grammar: 87,
      punctuation: 90,
      listening: 98,
      speaking: 86,
    }, },
    { "id": "S019", "name": "Daniel Martinez", "grade": "Grade 6", "score": 200, "accuracy": 91, "sessions": 28, "imageUrl": "p19.jpeg", "streak": 6, "hours": 54, skills: {
      vocabulary: 81,
      grammar: 72,
      punctuation: 74,
      listening: 90,
      speaking: 75,
    }, },
    { "id": "S020", "name": "Mia Rodriguez", "grade": "Grade 5", "score": 310, "accuracy": 93, "sessions": 48, "imageUrl": "p20.jpeg", "streak": 8, "hours": 82, skills: {
      vocabulary: 83,
      grammar: 65,
      punctuation: 62,
      listening: 96,
      speaking: 64,
    }, },
    { "id": "S021", "name": "Benjamin Scott", "grade": "Grade 9", "score": 340, "accuracy": 90, "sessions": 52, "imageUrl": "p21.jpeg", "streak": 12, "hours": 87,  skills: {
      vocabulary: 78,
      grammar: 68,
      punctuation: 67,
      listening: 90,
      speaking: 71,
    }, },
    { "id": "S022", "name": "Charlotte White", "grade": "Grade 4", "score": 220, "accuracy": 89, "sessions": 27, "imageUrl": "p22.jpeg", "streak": 4, "hours": 59, skills: {
      vocabulary: 80,
      grammar: 75,
      punctuation: 78,
      listening: 82,
      speaking: 79,
    }, },
    { "id": "S023", "name": "Henry Adams", "grade": "Grade 3", "score": 180, "accuracy": 86, "sessions": 23, "imageUrl": "p23.jpeg", "streak": 3, "hours": 47,  skills: {
      vocabulary: 92,
      grammar: 88,
      punctuation: 91,
      listening: 90,
      speaking: 89,
    }, },
    { "id": "S024", "name": "Amelia Johnson", "grade": "Grade 2", "score": 260, "accuracy": 92, "sessions": 37, "imageUrl": "p24.jpeg", "streak": 7, "hours": 68, skills: {
      vocabulary: 73,
      grammar: 67,
      punctuation: 65,
      listening: 86,
      speaking: 64,
    }, },
    { "id": "S025", "name": "Lucas Perez", "grade": "Grade 8", "score": 330, "accuracy": 94, "sessions": 50, "imageUrl": "p25.jpeg", "streak": 9, "hours": 89, skills: {
      vocabulary: 76,
      grammar: 74,
      punctuation: 79,
      listening: 97,
      speaking: 75,
    }, },
    { "id": "S026", "name": "Ella Brown", "grade": "Grade 5", "score": 280, "accuracy": 90, "sessions": 42, "imageUrl": "p26.jpeg", "streak": 6, "hours": 73, skills: {
      vocabulary: 85,
      grammar: 87,
      punctuation: 90,
      listening: 88,
      speaking: 86,
    }, },
    { "id": "S027", "name": "Jack Miller", "grade": "Grade 7", "score": 305, "accuracy": 93, "sessions": 46, "imageUrl": "p27.jpeg", "streak": 10, "hours": 77, skills: {
      vocabulary: 70,
      grammar: 69,
      punctuation: 72,
      listening: 71,
      speaking: 73,
    }, },
    { "id": "S028", "name": "Scarlett King", "grade": "Grade 6", "score": 240, "accuracy": 89, "sessions": 34, "imageUrl": "p28.jpeg", "streak": 5, "hours": 65, skills: {
      vocabulary: 94,
      grammar: 96,
      punctuation: 93,
      listening: 95,
      speaking: 97,
    }, },
    { "id": "S029", "name": "Alexander Green", "grade": "Grade 9", "score": 360, "accuracy": 96, "sessions": 58, "imageUrl": "p29.jpeg", "streak": 14, "hours": 98, skills: {
      vocabulary: 72,
      grammar: 75,
      punctuation: 70,
      listening: 74,
      speaking: 76,
    }, },
    { "id": "S030", "name": "Victoria Hall", "grade": "Grade 10", "score": 275, "accuracy": 87, "sessions": 31, "imageUrl": "p30.jpeg", "streak": 4, "hours": 64, skills: {
      vocabulary: 88,
      grammar: 66,
      punctuation: 69,
      listening: 95,
      speaking: 70,
    }, },
    { "id": "S031", "name": "Chloe Rivera", "grade": "Grade 8", "score": 210, "accuracy": 79, "sessions": 28, "imageUrl": "p31.jpeg", "streak": 5, "hours": 60, skills: {
      vocabulary: 75,
      grammar: 79,
      punctuation: 76,
      listening: 78,
      speaking: 77,
    }, },
    { "id": "S032", "name": "Ryan Walker", "grade": "Grade 6", "score": 185, "accuracy": 76, "sessions": 26, "imageUrl": "p32.jpeg", "streak": 4, "hours": 55, skills: {
      vocabulary: 71,
      grammar: 72,
      punctuation: 74,
      listening: 70,
      speaking: 75,
    }, },
    { "id": "S033", "name": "Harper Lewis", "grade": "Grade 5", "score": 172, "accuracy": 74, "sessions": 23, "imageUrl": "p33.jpeg", "streak": 3, "hours": 50, skills: {
      vocabulary: 93,
      grammar: 65,
      punctuation: 62,
      listening: 86,
      speaking: 64,
    }, },
    { "id": "S034", "name": "Evelyn Torres", "grade": "Grade 7", "score": 198, "accuracy": 78, "sessions": 30, "imageUrl": "p34.jpeg", "streak": 6, "hours": 58,  skills: {
      vocabulary: 70,
      grammar: 68,
      punctuation: 67,
      listening: 99,
      speaking: 71,
    }, },
    { "id": "S035", "name": "Matthew Young", "grade": "Grade 9", "score": 220, "accuracy": 75, "sessions": 32, "imageUrl": "p35.jpeg", "streak": 5, "hours": 63, skills: {
      vocabulary: 76,
      grammar: 74,
      punctuation: 79,
      listening: 77,
      speaking: 75,
    }, },
    { "id": "S036", "name": "Zoey Hernandez", "grade": "Grade 4", "score": 165, "accuracy": 73, "sessions": 20, "imageUrl": "p36.jpeg", "streak": 2, "hours": 48, skills: {
      vocabulary: 79,
      grammar: 67,
      punctuation: 65,
      listening: 86,
      speaking: 64,
    }, },
    { "id": "S037", "name": "Nathan Baker", "grade": "Grade 3", "score": 140, "accuracy": 69, "sessions": 18, "imageUrl": "p37.jpeg", "streak": 2, "hours": 45, skills: {
      vocabulary: 92,
      grammar: 88,
      punctuation: 91,
      listening: 90,
      speaking: 89,
    }, },
    { "id": "S038", "name": "Lily Gonzalez", "grade": "Grade 2", "score": 120, "accuracy": 66, "sessions": 15, "imageUrl": "p38.jpeg", "streak": 1, "hours": 40, skills: {
      vocabulary: 70,
      grammar: 73,
      punctuation: 68,
      listening: 75,
      speaking: 71,
    }, },
    { "id": "S039", "name": "Owen Carter", "grade": "Grade 5", "score": 100, "accuracy": 62, "sessions": 14, "imageUrl": "p39.jpeg", "streak": 1, "hours": 38, skills: {
      vocabulary: 82,
      grammar: 78,
      punctuation: 80,
      listening: 85,
      speaking: 84,
    }, },
    { "id": "S040", "name": "Aria Mitchell", "grade": "Grade 1", "score": 90, "accuracy": 65, "sessions": 12, "imageUrl": "p40.jpeg", "streak": 1, "hours": 35, skills: {
      vocabulary: 70,
      grammar: 69,
      punctuation: 72,
      listening: 71,
      speaking: 73,
    }, }
];

export default students;


export const user = {
  profileSettings: {
    fullName: "Admin User",
    email: "admin@example.com",
    phoneNumber: "+49-178-777-000",
  },
  systemSettings: {
    language: "English",
    timezone: TimeZone
  }, 
  notification: {
    email: "email",
    reports: "reports",
    alert: "alerts"
  },
  dataManagement: {
    student: {
        id: "",
        name: "",
        grade: "",
        imageUrl: "",
        score: 0,
        accuracy: 0,
        sessions: 0,
        streak: 0,
        hours: 0,
        skills: {
          vocabulary: 0,
          grammar: 0,
          punctuation: 0,
          listening: 0,
          speaking: 0
        }
      },
  }
}
